In [1]:
from utils import generate_plot_catalog
import pandas as pd

In [2]:
df = dict()
for casename in [
    "g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001",
    "g.e22.G1850ECO_JRA_HR.TL319_t13.003",
    "g.e22.G1850ECO_JRA_HR.TL319_t13.004",
]:
    df[casename] = pd.DataFrame({})
    for plottype in [
        "histogram",
        "summary_map",
        "time_series",
        "trend_hist",
        "trend_map",
    ]:
        print(f"Generating csv for {plottype} plots in {casename}")
        df[casename] = pd.concat(
            [
                df[casename],
                generate_plot_catalog(
                    "./",
                    image_dir_name=f"images/{casename}/{plottype}",
                    use_full_path=False,
                ),
            ]
        )
    df[casename].to_csv(
        f"images/{casename}/png_catalog.csv",
        compression=None,
        index=False,
    )

Generating csv for histogram plots in g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001
Generating csv for summary_map plots in g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001
Generating csv for time_series plots in g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001
Generating csv for trend_hist plots in g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001
Found 0 files with extension=.json in images/g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001/trend_hist.
Generating csv for trend_map plots in g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001
Found 0 files with extension=.json in images/g.e22b05.G1850ECOIAF_JRA.TL319_g17.cocco.001/trend_map.
Generating csv for histogram plots in g.e22.G1850ECO_JRA_HR.TL319_t13.003
Generating csv for summary_map plots in g.e22.G1850ECO_JRA_HR.TL319_t13.003
Generating csv for time_series plots in g.e22.G1850ECO_JRA_HR.TL319_t13.003
Generating csv for trend_hist plots in g.e22.G1850ECO_JRA_HR.TL319_t13.003
Generating csv for trend_map plots in g.e22.G1850ECO_JRA_HR.TL319_t13.003
Generating csv for histogram plots in g.e22.G1850ECO_JRA_HR.TL319_t13.004
Generating csv for summary_map plots in g.e22.G1850ECO_JRA_HR.TL319_t13.004
Generating csv for time_series plots in g.e22.G1850ECO_JRA_HR.TL319_t13.004
Generating csv for trend_hist plots in g.e22.G1850ECO_JRA_HR.TL319_t13.004
Generating csv for trend_map plots in g.e22.G1850ECO_JRA_HR.TL319_t13.004

In [3]:
df["g.e22.G1850ECO_JRA_HR.TL319_t13.004"]

,plot_type,varname,casename,apply_log10,time_period,sel_dict,filepath,date
0,histogram,CaCO3_FLUX_100m,g.e22.G1850ECO_JRA_HR.TL319_t13.004,False,0001-01-01_0001-12-31,{},histogram/CaCO3_FLUX_100m.0001-01-01_0001-12-3...,NaN
1,histogram,CaCO3_FLUX_100m,g.e22.G1850ECO_JRA_HR.TL319_t13.004,True,0001-01-01_0001-12-31,{},histogram/CaCO3_FLUX_100m.0001-01-01_0001-12-3...,NaN
2,histogram,CaCO3_FLUX_100m,g.e22.G1850ECO_JRA_HR.TL319_t13.004,False,0002-01-01_0002-12-31,{},histogram/CaCO3_FLUX_100m.0002-01-01_0002-12-3...,NaN
3,histogram,CaCO3_FLUX_100m,g.e22.G1850ECO_JRA_HR.TL319_t13.004,True,0002-01-01_0002-12-31,{},histogram/CaCO3_FLUX_100m.0002-01-01_0002-12-3...,NaN
4,histogram,CaCO3_FLUX_100m,g.e22.G1850ECO_JRA_HR.TL319_t13.004,False,0003-01-01_0003-12-31,{},histogram/CaCO3_FLUX_100m.0003-01-01_0003-12-3...,NaN
...,...,...,...,...,...,...,...,...
25,trend_map,SiO3,g.e22.G1850ECO_JRA_HR.TL319_t13.004,NaN,0002-01-01_0004-12-31,{'basins': 'Atlantic'},trend_map/SiO3.0002-01-01_0004-12-31.basins--A...,NaN
26,trend_map,SiO3,g.e22.G1850ECO_JRA_HR.TL319_t13.004,NaN,0002-01-01_0004-12-31,{'basins': 'Global'},trend_map/SiO3.0002-01-01_0004-12-31.basins--G...,NaN
27,trend_map,SiO3,g.e22.G1850ECO_JRA_HR.TL319_t13.004,NaN,0002-01-01_0004-12-31,{'basins': 'Indian'},trend_map/SiO3.0002-01-01_0004-12-31.basins--I...,NaN
28,trend_map,SiO3,g.e22.G1850ECO_JRA_HR.TL319_t13.004,NaN,0002-01-01_0004-12-31,{'basins': 'Pacific'},trend_map/SiO3.0002-01-01_0004-12-31.basins--P...,NaN
29,trend_map,SiO3,g.e22.G1850ECO_JRA_HR.TL319_t13.004,NaN,0002-01-01_0004-12-31,{'z_t': '35109.35'},trend_map/SiO3.0002-01-01_0004-12-31.z_t--3510...,NaN

In [4]:
df["g.e22.G1850ECO_JRA_HR.TL319_t13.004"]["filepath"].to_list()[0]

'histogram/CaCO3_FLUX_100m.0001-01-01_0001-12-31.png'